### PR TITLE
Modify page routing and nav to allow versions

### PR DESCRIPTION
**Pull request by jimlambie**
This PR introduces versioning of product documentation.

To create a new version of a document:

1. rename the existing `latest.md` to the version it refers to
2. add a `version` property to the frontmatter for the version it refers to
3. add a new `latest.md` for the new version

**docs/api/1.3.0.md**
```
---
title: API 1.3.0
order: 1
published: true
product: api
version: 1.3.0
---

```

### CODE REVIEW

**Comment by abovedave** [comment]
Lovely idea. Reviewing

**Comment by eduardoboucas** [comment]
This is great, thanks for making it happen! 👑 

Will `/api` redirect to `/api/latest`?

**Comment by jimlambie** [comment]
@eduardoboucas good point, I'll add the redirects for each product

**Comment by eduardoboucas** [comment]
@jimlambie @abovedave are you happy for this to be merged?

**Pull request merged**
